kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: my-frontend
      image: busybox:1.28
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-inline-vol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-inline-vol
      csi:
        driver: emptydirclone.mriyam.dev
