name: emptydirclone-e2e-tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  packages: write

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E tests
        run: echo "Hello, E2E"
