name: emptydirclone-e2e-tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  actions: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/image-build-push.yaml
    secrets: inherit
  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run tests
        working-directory: ./emptyDirClone
        run: |
          echo "Using tag: ${{ needs.build-image.outputs.tag }}"
          sed -i "s/emptydirclone:.*/emptydirclone:${{ needs.build-image.outputs.tag }}/" deploy/daemonset.yaml
          make e2e E2E_TEST_ARGS="--fail-fast --v 6"
      -
        name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: ./emptyDirClone/tests/e2e/logs/
      -
        name: Cleanup
        if: always()
        run: |
          for i in $(kind get clusters); do kind delete cluster --name $i; done
